### ISSUE TITLE
Code generation not configured error

### ISSUE THREAD

**Issue by RuarriS** [aws-amplify/amplify-codegen#121]
** Which Category is your question related to? **
CLI Codegen
** What AWS Services are you utilizing? **
Appsync
** Provide additional details e.g. code snippets **

I have been using the cli to build a project for some time, and recently updated the schema in Appsync. When attempting to run `amplify codegen` I receive the error "code generation is not configured. Configure it by running $amplify codegen add". 

Running codegen configure does modify my current .graphqlconfig.yml file, so it seems only trying to update creates issues. 

Any help updating?

**Comment by hirenumradia** [comment]
@kaustavghosh06  I have an update on this today. So I have `codegen` working by running `amplify add codegen --apiId xxxxx`

It stops working if I run `amplify env pull x` or `amplify env checkout x`. 

Once it stops working, I am stuck in this loop between the CLI saying

`code generation is not configured. Configure it by running $amplify codegen add` 

and 

`code generation is not configured. Configure it by running $amplify codegen add`

the only way to fix this is to manually delete the file `.graphqlconfig.yml` and then re-run `amplify add codegen --apiId xxxxx`.

This lets me go through the process of adding the API again where codegen works correctly. 

As I have automated a lot of our CICD workflow, this issue is really critical for us to be able to use amplify reliably. We have an existing API built using AWS CDK and we need to make sure that we can update the API and run codegen afterwards.

With codegen breaking after pulling the backend amplify environment, it makes deployment to amplify scary.

**Comment by AaronZyLee** [comment]
@hirenumradia Sorry for the conflicting error messaging. There is a bug for the codegen error messages. In your scenario it is the `api` metadata rather than the codegen project that is not configured. I try to reproduce the issue by using `amplify env checkout xx` and find that the api metadata is not included in the meta after running the command. Since the old codegen project exists and currently codegen only supports one api resource, I would suggest a temporary solution that you could run the following commands to reset the codegen and apis.
```
$ amplify codegen remove
$ amplify codegen add apiId xxx
```
On the other hand, we also need to change the error message to give correct instructions. In this case the error message should be changed to the proper one like

> The api resource is not found but codegen is configured. Reset the codegen by $amplify codegen remove and $amplify codegen add --apiId xxxx

**Comment by hirenumradia** [comment]
@AaronZyLee Thanks for unblocking me. This really helps, along with the headless changes you are putting in. It will really help us close the loop between CDK and Amplify. Thanks :)

That error would be helpful!
