### ISSUE TITLE
After updating the CLI to the latest when amplify push api it's doesn't ask me anymore to update the api.service.ts

### ISSUE THREAD

**Issue by iuyt9003** [aws-amplify/amplify-codegen#139]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

15.0.0

### Amplify CLI Version

4.461

### What operating system are you using?

Windows

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

After updating the CLI to the latest when amplify push API it's doesn't ask me anymore to update the api.service.ts.
We using some of the auto-generated API service queries. and it's stopped to ask if to update it and to update it. 

### Expected behavior

To ask if you want to update the API.service.ts. or to automatic update and on my side i will choose if to push the files. 
or a flag so i will be able to add.

### Reproduction steps

1. Change your amplify graphql schema
2. Amplify push 
3. will not ask you if to update the API.service.ts

**Comment by AaronZyLee** [comment]
I am not able to reproduce this issue. Could you provide more contents so that I could have a better picture of the issue:

1. Which schema file did you change?(path is supposed to be `amplify/backend/api/${api_name}/schema.graphql`
2. If you do the first one, could you run `amplify status` before the push to check if the API category get the `UPDATE` status?
3. If the two above have no problem, could you provide your `.graphqlconfig.yml` file which should be under your project root.

Since the push does not update your schema, I suggest a temporary solution to run `amplify codegen` manually to update your `API.service.ts`

**Comment by iuyt9003** [comment]
For the 2 above configured good ( 1,2 ) there is a location and it's on the right path. 

About the graphql config I am sending it now : 
![image](https://user-images.githubusercontent.com/23431551/113444290-45fa3800-93fc-11eb-8343-409aaed68dd0.png)

Amplify Codegen did the magic for now :) 
and generated the API.service.ts

much thanks!
