### ISSUE TITLE
amplify codegen model adds non-existent Id field and ignores the key definition

### ISSUE THREAD

**Issue by asyschikov** [aws-amplify/amplify-codegen#42]
**Describe the bug**
While generating the model files (Java/Android in my case) the codegen tool on its own adds Id field to the model, while it is NOT in the schema. Of course that doesn't work down the line because this field does not exist. The problem is here: https://github.com/aws-amplify/amplify-cli/blob/9951402777b047277e6e05c6cb84fea92c238e82/packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts#L199 I used `@key` directive without the key name to specify HK, which is also not supported.  This is not as much as a bug but just really strange implementation that on purpose generates invalid models. Also how is that supposed to work with models that have HK + SK? Code sample down below.
```
type UserProfile @model @key(fields: ["userId"]) {
  userId: ID!
}
```
Result:
```
@ModelConfig(pluralName = "UserProfiles")
@Index(name = "undefined", fields = {"userId"})
public final class UserProfile implements Model {
  public static final QueryField ID = field("id");
  public static final QueryField USER_ID = field("userId");
```

Expectation: the codegen model tool picks up that the HK is called userId and uses it accordingly, instead of generating invalid models.

**Amplify CLI Version**
4.6.0

**To Reproduce**
Create a model with  HK other then Id and run amplify codegen model

**Expected behavior**
The specified column is used as HK.

**Comment by Monik09** [comment]
dropping the table and recreating it worked for me as it was a small table.

**Comment by alharris-at** [comment]
Hi, this is a known gap in DataStore interacting with a customer Primary Key today. If you refer to the JavaScript DataStore docs https://docs.amplify.aws/lib/datastore/relational/q/platform/js/ we do call out that you'll need to explicitly set the id column as well. This will only be supported for the new v2 transformer once released, so in order to take advantage you'll need to upgrade. In the interim, similar to what the docs suggest you'll need to explicitly set your `id` column to the same as your defined primary key. Closing this issue and will track release of v2 support in https://github.com/aws-amplify/amplify-codegen/issues/424
