### ISSUE TITLE
Can you change the location of where models are generated when using amplify codegen models?

### ISSUE THREAD

**Issue by cmaycumber** [aws-amplify/amplify-codegen#58]
**Which Category is your question related to?**
Datastore, Amplify codegen models

Right now when I run amplify codegen models, the models are currently created in the src/models directory. Is there any way to change this?

I imagine that it would act similarly to how the normal codegen where the file location can be changed in the .graphqlconfig.yml

**Comment by phani-srikar** [comment]
Hi @cmaycumber. Thank you for requesting this. We are tracking this feature here #55. Closing this in favor of that.

**Comment by Gab1988** [comment]
Not an expert on bash but this worked for me to move the models from "./models" to "./src/models" 

`"aws-amplify-generate-models-at-path": "amplify codegen model &&  files=$(find ./models -type f | wc -l) && if [ $files -eq 4 ]; then rm -r ./src/models && mv ./models ./src && rm -rf ./models; fi"`

Since I run this command on my CI pipeline I also added the check to verify that the original folder has 4 files which suggests the schema creation worked

**Comment by jpslav** [comment]
I found a `SourceDir` setting in `amplify/.config/project-config.json`... it was `src`, and when I changed it to my desired folder (`app`), then `amplify codegen models` put the models in `app`. Haven't tried setting `SourceDir` to `.` but that might work.

**Comment by codenimble** [comment]
Any update here? Amplify should allow you to specify a root for all their generated files (including ui-components). I find it rather annoying that they have partially customized configurations. I already had a 'models' folder.

**Comment by dJani97** [comment]
It's tracked here: https://github.com/aws-amplify/amplify-codegen/issues/55

> This feature is now supported. You can specify an --output-dir when running amplify codegen models in order to specify where the files will be rendered. Marking this issue as closed.
