### ISSUE TITLE
Supply more resource to resolving bugs on amplify-codegen

### ISSUE THREAD

**Issue by gruckion** [aws-amplify/amplify-codegen#96]
Currently there is a ratio of 26/2 for the open/close ratio. This is not a good sign during the next retro can you discuss ways that this can be improved? Are these issues being review and prioritised? Are they actively being delay by some other deliverable? Is more resource needed? Can some of these issues just be closed?

Thank you for all your efforts, keep up the good work!

**Comment by AaronZyLee** [comment]
Thanks for the report. `amplify-codegen` is the last package we plan to take the ownership from CLI and the process is about to finish after this PR https://github.com/aws-amplify/amplify-cli/pull/6730 gets merged and released. However we transfer the issues related to that package ahead of the migration of package but we cannot start fixing issues unless we have the full ownership of it. That's why the issues with `amplify-codegen` tags are not resolved mostly. 

In the meantime, we do start working on resolving other packages issues which we already have full ownership(tagged with `model-gen`, `type-gen` and `doc-gen`). We have make much progress by closing 20+ issues out of 40+ issues orignally transferred from CLI team with some ongoing PRs to solve more. 

The migration of `amplify-codegen` will be finished early next week and we will focus on the related issues. As a matter of fact, the team already has a discussion on the remaining issues. While we could try to fix bugs as many as possible, most of the issues are feature-request/enhancement and those will bring breaking changes to current workflow. Hence, we decide to re-design the `amplify-codegen` and we tag the related issues with `pluggin-support`. An RFC for the codegen redesign will soon be posted in the early March and we welcome all the customers to share their thoughts and experience so that we can have more context to move on.

Thanks again for bringing this out and we look forward for your thoughts on the upcoming RFC. I close this issue for now but feel free to open it if you have any unresolved questions.
